#!/usr/bin/env bash
#Installing nginx server listening on port 80.
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!"   | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
