#!/usr/bin/env bash
#Configuring Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update 
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name_;/a rewrite^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
