#!/usr/bin/env bash
#Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y update 
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name_;/a rewrite^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
sudo sed -i "server_name+;/a error_page 404 /404.html;\nlocation = /404.html {\root /var/www/html;\niternal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
